# Generated by Django 3.0 on 2020-02-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20200220_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='Date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
