# Generated by Django 3.0 on 2020-02-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20200221_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge_questions',
            old_name='Question',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='challenge_questions',
            unique_together={('challenge', 'question')},
        ),
    ]
