# Generated by Django 3.0 on 2020-02-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20200221_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tinput', models.TextField()),
                ('Toutput', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='question',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='Description',
            field=models.TextField(max_length=5520),
        ),
        migrations.DeleteModel(
            name='submittedcodes',
        ),
        migrations.DeleteModel(
            name='testcases',
        ),
        migrations.AddField(
            model_name='question_testcase',
            name='testcase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.Testcase'),
        ),
        migrations.AlterUniqueTogether(
            name='question_testcase',
            unique_together={('testcase', 'question')},
        ),
    ]
