# Generated by Django 3.0 on 2020-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20200228_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_testcase',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question_testcase',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
