# Generated by Django 3.0 on 2020-03-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20200303_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='count',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='submitted_code',
        ),
    ]
