# Generated by Django 3.0 on 2020-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20200305_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
