# Generated by Django 3.0 on 2020-03-16 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0014_auto_20200316_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='demoCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.TextField(default='#include<stdio.h>\n\nint main() {\n    \n    printf("");\n    \n}\n', max_length=1000000)),
                ('cpp_code', models.TextField(default='#include <iostream>\n\nusing namespace std;\n\nint main() {\n    \n    cout<<"";\n}\n', max_length=1000000)),
                ('csharp_code', models.TextField(default='//Note don\'t change the class name \nusing System;\n\nclass Program\n{\n    static void Main() {\n        Console.Write("");\n    }\n}\n', max_length=1000000)),
                ('java_code', models.TextField(default='//NOTE: Don\'t change class name\npublic class MyClass {\n    public static void main(String args[]) {\n      System.out.println("" );\n    }\n}\n', max_length=1000000)),
                ('python_code', models.TextField(default="if __name__ == '__main__':\n", max_length=1000000)),
                ('submitted_code', models.TextField(default='NA', max_length=1000000)),
                ('score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
