# Generated by Django 3.0 on 2020-03-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_auto_20200316_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='democodes',
            name='question',
        ),
    ]
