# Generated by Django 3.0.4 on 2021-07-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0018_auto_20210713_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='')),
                ('language', models.TextField(default='')),
                ('testcase_status', models.TextField(default='')),
                ('total_score', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Candidate')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Question')),
            ],
        ),
    ]
