# Generated by Django 3.0.4 on 2022-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0020_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
